### PR TITLE
Fixed bugs + some other improvements

### PR DESCRIPTION
**Pull request by jvdp1**
Here are some proposals for fixing bugs and improvements.
Each commit should be independent, and so enabling cherry-picking

### CODE REVIEW

**Comment by milancurcic** [comment]
Thanks @jvdp1 for these changes, I think they're overall good changes. I'll discuss with @beatrixparis on how to get more organized with reviewing and merging PRs (I don't have merge privilege yet).

**Review by beatrixparis — APPROVED** [review]
Thanks @jvdp1 for these changes.

**Comment by beatrixparis** [comment]
Thanks Milan. I approved the changes. Let’s discuss how to give you rights on CMS  when we meet this Wednesday.

Claire B. Paris
Sent from iPhone - apologies for typos

Le 30 mai 2024 à 16:00, Milan Curcic ***@***.***> a écrit :

Thanks @jvdp1<https://urldefense.com/v3/__https://github.com/jvdp1__;!!KVu0SnhVq1hAFvslES2Y!OgumbYjIQKnoxDFx5KyflTr_AZ5nzjE4ThaOtchZK5kX1YKaaCuo3g1EOXHyXWgVM4T1kotLQN7AoH15qrRICHKpOA56$> for these changes, I think they're overall good changes

**Comment by milancurcic** [comment]
Hi Claire, you closed this PR without merging it, so the changes are not applied. I don't think you meant to do that. If you want to merge these changes into the `master` branch, there should be a button here at the bottom that says "Re-open" (or similar), and then there will be a green button that says "Merge pull request" (or similar).

**Review by milancurcic — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
